name: fama_if
description: "FamaIF - Ranking de Popularidade dos Alunos (PiramidGame IFPR-Pgua)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  sqflite_common_ffi: ^2.3.0
  
  cupertino_icons: ^1.0.8

  # Navegação
  go_router: ^17.1.0

  # Gerência de estado e reatividade
  signals_flutter: ^6.3.0

  # Injeção de dependências
  auto_injector: ^2.1.1

  # Banco de dados SQLite (substitui o shared_preferences)
  sqflite: ^2.3.3
  path: ^1.9.0

  # Comparação por valor nas entidades
  equatable: ^2.0.8

  # Geração de ids únicos
  uuid: ^4.5.1

  # Formatação de datas
  intl: ^0.20.2

  # Tipografia personalizada
  google_fonts: ^6.2.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
